import { Business, Invoice, Payslip } from '@/types'
import { formatTZS, formatDate, monthLabel } from './utils'
import { existsSync } from 'fs'

// ============================================================
// PDF generation via Puppeteer
// Uses @sparticuz/chromium for serverless environments
// ============================================================

async function getBrowser() {
  // In production (Vercel/serverless), use stripped Chromium
  if (process.env.NODE_ENV === 'production') {
    const chromium = (await import('@sparticuz/chromium')).default
    const puppeteer = await import('puppeteer-core')
    return puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath(),
      headless: true,
    })
  }

  // Local dev: use a local Chrome/Chromium executable with puppeteer-core.
  const puppeteer = await import('puppeteer-core')
  const executablePath = findLocalChrome()

  return puppeteer.launch({
    headless: true,
    executablePath,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  })
}

function findLocalChrome() {
  const candidates = [
    process.env.PUPPETEER_EXECUTABLE_PATH,
    process.platform === 'win32'
      ? 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'
      : null,
    process.platform === 'darwin'
      ? '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
      : null,
    '/usr/bin/google-chrome',
    '/usr/bin/chromium-browser',
    '/usr/bin/chromium',
  ].filter(Boolean) as string[]

  const executablePath = candidates.find((path) => existsSync(path))

  if (!executablePath) {
    throw new Error(
      'Chrome executable not found. Install Google Chrome locally or set PUPPETEER_EXECUTABLE_PATH.'
    )
  }

  return executablePath
}

export async function htmlToPDF(html: string): Promise<Buffer> {
  const browser = await getBrowser()
  try {
    const page = await browser.newPage()
    await page.setContent(html, { waitUntil: 'networkidle0' })
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '15mm', right: '15mm', bottom: '15mm', left: '15mm' },
    })
    return Buffer.from(pdf)
  } finally {
    await browser.close()
  }
}

export function renderInvoiceFallbackPDF(invoice: Invoice, business: Business): Buffer {
  const lines = [
    pdfLine(business.name, 18, true),
    pdfLine(joinPresent([business.address, business.phone, business.email]), 9),
    pdfLine(joinPresent([business.tin ? `TIN: ${business.tin}` : '', business.vrn ? `VRN: ${business.vrn}` : '']), 9),
    pdfSpacer(),
    pdfLine(`INVOICE ${invoice.number}`, 16, true),
    pdfLine(`Client: ${invoice.client_name}`, 11, true),
    pdfLine(joinPresent([invoice.client_phone, invoice.client_email, invoice.client_tin ? `TIN: ${invoice.client_tin}` : '']), 9),
    pdfLine(`Invoice date: ${formatDate(invoice.created_at)}`, 9),
    pdfLine(`Due date: ${invoice.due_date ? formatDate(invoice.due_date) : 'As soon as possible'}`, 9),
    pdfSpacer(),
    pdfLine('Items', 12, true),
    ...invoice.items.flatMap((item) => [
      pdfLine(`${item.description}`, 10, true),
      pdfLine(`Qty ${item.qty} x ${formatTZS(item.unit_price)} = ${formatTZS(item.amount)}`, 9),
    ]),
    pdfSpacer(),
    pdfLine(`Subtotal: ${formatTZS(invoice.subtotal)}`, 10),
    pdfLine(`VAT (${invoice.vat_rate}%): ${formatTZS(invoice.vat_amount)}`, 10),
    pdfLine(`Grand total: ${formatTZS(invoice.total)}`, 13, true),
  ]

  if (invoice.payment_link) {
    lines.push(pdfSpacer(), pdfLine('Payment reference', 11, true), pdfLine(invoice.payment_link, 9))
  }

  if (invoice.notes) {
    lines.push(pdfSpacer(), pdfLine('Notes', 11, true), pdfLine(invoice.notes, 9))
  }

  lines.push(
    pdfSpacer(),
    pdfLine(`Generated by Blackwhite for ${business.name}`, 8)
  )

  return createBasicTextPDF(lines)
}

export function renderPayslipFallbackPDF(payslip: Payslip, business: Business): Buffer {
  const lines = [
    pdfLine(business.name, 18, true),
    pdfLine(joinPresent([business.address, business.tin ? `TIN: ${business.tin}` : '']), 9),
    pdfSpacer(),
    pdfLine(`PAYSLIP - ${monthLabel(payslip.month)}`, 16, true),
    pdfLine(`Employee: ${payslip.employee_name}`, 11, true),
    pdfLine(joinPresent([payslip.employee_id ? `ID: ${payslip.employee_id}` : '', payslip.position || '']), 9),
    pdfSpacer(),
    pdfLine('Earnings', 12, true),
    pdfLine(`Basic salary: ${formatTZS(payslip.basic_salary)}`, 10),
    ...payslip.allowances.map((item) => pdfLine(`${item.name}: ${formatTZS(item.amount)}`, 10)),
    pdfLine(`Gross pay: ${formatTZS(payslip.gross)}`, 11, true),
    pdfSpacer(),
    pdfLine('Deductions', 12, true),
    pdfLine(`PAYE: ${formatTZS(payslip.paye)}`, 10),
    pdfLine(`NSSF employee: ${formatTZS(payslip.nssf_employee)}`, 10),
    ...payslip.other_deductions.map((item) => pdfLine(`${item.name}: ${formatTZS(item.amount)}`, 10)),
    pdfLine(`Total deductions: ${formatTZS(payslip.total_deductions)}`, 11, true),
    pdfSpacer(),
    pdfLine(`Net pay: ${formatTZS(payslip.net_pay)}`, 14, true),
    pdfLine(`NSSF employer contribution: ${formatTZS(payslip.nssf_employer)}`, 9),
    pdfSpacer(),
    pdfLine(`Generated by Blackwhite for ${business.name}`, 8),
  ]

  return createBasicTextPDF(lines)
}

type BasicPdfLine = {
  text: string
  size: number
  bold: boolean
  spacer?: boolean
}

function pdfLine(text: string, size = 10, bold = false): BasicPdfLine {
  return { text, size, bold }
}

function pdfSpacer(): BasicPdfLine {
  return { text: '', size: 8, bold: false, spacer: true }
}

function createBasicTextPDF(lines: BasicPdfLine[]): Buffer {
  const pageWidth = 595.28
  const pageHeight = 841.89
  const marginX = 42
  const marginTop = 48
  const marginBottom = 42
  const usableWidth = pageWidth - marginX * 2
  const pages: BasicPdfLine[][] = [[]]
  let y = pageHeight - marginTop

  for (const line of lines) {
    const wrappedLines = line.spacer ? [''] : wrapText(line.text, Math.max(24, Math.floor(usableWidth / (line.size * 0.52))))

    for (const text of wrappedLines) {
      const height = line.spacer ? 10 : line.size + 5
      if (y - height < marginBottom) {
        pages.push([])
        y = pageHeight - marginTop
      }

      pages[pages.length - 1].push({ ...line, text })
      y -= height
    }
  }

  const objects: string[] = []
  const addObject = (body: string) => {
    objects.push(body)
    return objects.length
  }

  const catalogId = addObject('<< /Type /Catalog /Pages 2 0 R >>')
  const pagesId = addObject('')
  const regularFontId = addObject('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>')
  const boldFontId = addObject('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>')
  const pageIds: number[] = []

  pages.forEach((pageLines) => {
    const content = renderPdfPageContent(pageLines, pageHeight, marginX, marginTop)
    const contentId = addObject(`<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`)
    const pageId = addObject(
      `<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] ` +
        `/Resources << /Font << /F1 ${regularFontId} 0 R /F2 ${boldFontId} 0 R >> >> ` +
        `/Contents ${contentId} 0 R >>`
    )
    pageIds.push(pageId)
  })

  objects[pagesId - 1] = `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(' ')}] /Count ${pageIds.length} >>`

  const chunks = ['%PDF-1.4\n']
  const offsets: number[] = [0]

  objects.forEach((body, index) => {
    offsets.push(Buffer.byteLength(chunks.join('')))
    chunks.push(`${index + 1} 0 obj\n${body}\nendobj\n`)
  })

  const xrefOffset = Buffer.byteLength(chunks.join(''))
  chunks.push(`xref\n0 ${objects.length + 1}\n`)
  chunks.push('0000000000 65535 f \n')
  offsets.slice(1).forEach((offset) => {
    chunks.push(`${String(offset).padStart(10, '0')} 00000 n \n`)
  })
  chunks.push(`trailer\n<< /Size ${objects.length + 1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`)

  return Buffer.from(chunks.join(''), 'utf8')
}

function renderPdfPageContent(lines: BasicPdfLine[], pageHeight: number, marginX: number, marginTop: number) {
  let y = pageHeight - marginTop
  const commands: string[] = ['BT']

  lines.forEach((line) => {
    if (line.spacer) {
      y -= 10
      return
    }

    commands.push(`/${line.bold ? 'F2' : 'F1'} ${line.size} Tf`)
    commands.push(`1 0 0 1 ${marginX} ${y.toFixed(2)} Tm`)
    commands.push(`(${escapePdfText(line.text)}) Tj`)
    y -= line.size + 5
  })

  commands.push('ET')
  return commands.join('\n')
}

function wrapText(text: string, maxChars: number) {
  const clean = cleanPdfText(text)
  if (clean.length <= maxChars) return [clean]

  const words = clean.split(/\s+/)
  const lines: string[] = []
  let current = ''

  words.forEach((word) => {
    if (!current) {
      current = word
      return
    }

    if (`${current} ${word}`.length <= maxChars) {
      current = `${current} ${word}`
    } else {
      lines.push(current)
      current = word
    }
  })

  if (current) lines.push(current)
  return lines
}

function cleanPdfText(text: string) {
  return String(text || '')
    .normalize('NFKD')
    .replace(/[^\x20-\x7E]/g, '')
}

function escapePdfText(text: string) {
  return cleanPdfText(text).replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)')
}

function joinPresent(values: (string | null | undefined)[]) {
  return values.filter(Boolean).join(' | ')
}

async function renderLogoHTML(business: Business, className: string) {
  const fallback = `<div class="logo-placeholder">${escapeHtml((business.name || 'B').charAt(0))}</div>`

  if (!business.logo_url) return fallback

  const src = await logoUrlToDataUri(business.logo_url)
  if (!src) return fallback

  return `<img src="${src}" alt="${escapeHtml(business.name)}" class="${className}" />`
}

async function logoUrlToDataUri(url: string) {
  try {
    const response = await fetch(url, { cache: 'no-store' })
    if (!response.ok) return url

    const contentType = response.headers.get('content-type') || 'image/png'
    if (!contentType.startsWith('image/')) return url

    const arrayBuffer = await response.arrayBuffer()
    if (arrayBuffer.byteLength > 2_500_000) return url

    return `data:${contentType};base64,${Buffer.from(arrayBuffer).toString('base64')}`
  } catch {
    return url
  }
}

function escapeHtml(value: string | number | null | undefined) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

// ============================================================
// Invoice HTML Template
// ============================================================
export async function renderInvoiceHTML(invoice: Invoice, business: Business): Promise<string> {
  const itemsHTML = invoice.items
    .map(
      (item) => `
      <tr>
        <td class="desc">${escapeHtml(item.description)}</td>
        <td class="num">${escapeHtml(item.qty)}</td>
        <td class="num">${formatTZS(item.unit_price)}</td>
        <td class="num amount">${formatTZS(item.amount)}</td>
      </tr>`
    )
    .join('')

  const logoHTML = await renderLogoHTML(business, 'logo')

  const statusBadge = {
    draft: '<span class="badge badge-gray">Rasimu</span>',
    sent: '<span class="badge badge-blue">Imetumwa</span>',
    paid: '<span class="badge badge-green">Imelipwa ✓</span>',
    overdue: '<span class="badge badge-red">Imechelewa</span>',
  }[invoice.status]

  return `<!DOCTYPE html>
<html lang="sw">
<head>
<meta charset="UTF-8">
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px; color: #1a1a1a; background: #fff; }
  .page { padding: 0; }

  /* Header */
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 32px; padding-bottom: 20px; border-bottom: 2px solid #1a1a1a; }
  .brand { display: flex; align-items: center; gap: 12px; }
  .logo { height: 52px; width: auto; object-fit: contain; }
  .logo-placeholder { width: 52px; height: 52px; background: #1a7a4a; border-radius: 8px; display: flex; align-items: center; justify-content: center; color: white; font-size: 24px; font-weight: 700; }
  .biz-name { font-size: 18px; font-weight: 700; color: #1a1a1a; letter-spacing: -0.3px; }
  .biz-meta { font-size: 9.5px; color: #666; margin-top: 3px; line-height: 1.6; }
  .invoice-meta { text-align: right; }
  .invoice-title { font-size: 28px; font-weight: 800; letter-spacing: -1px; color: #1a7a4a; text-transform: uppercase; }
  .invoice-number { font-size: 11px; font-weight: 600; color: #444; margin-top: 4px; }

  /* Parties */
  .parties { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin-bottom: 28px; }
  .party-label { font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #888; margin-bottom: 5px; }
  .party-name { font-size: 13px; font-weight: 700; color: #1a1a1a; margin-bottom: 3px; }
  .party-detail { font-size: 9.5px; color: #555; line-height: 1.6; }

  /* Dates row */
  .dates-row { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; background: #f5f5f2; border-radius: 8px; padding: 12px 16px; margin-bottom: 24px; }
  .date-item { }
  .date-label { font-size: 9px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.07em; color: #888; margin-bottom: 3px; }
  .date-value { font-size: 11px; font-weight: 600; color: #1a1a1a; }

  /* Items table */
  table { width: 100%; border-collapse: collapse; margin-bottom: 0; }
  thead tr { background: #1a1a1a; }
  thead th { padding: 9px 12px; text-align: left; font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.07em; color: #fff; }
  thead th.num { text-align: right; }
  tbody tr { border-bottom: 1px solid #ebebeb; }
  tbody tr:nth-child(even) { background: #fafafa; }
  tbody td { padding: 9px 12px; font-size: 10.5px; color: #1a1a1a; }
  td.desc { color: #222; }
  td.num { text-align: right; font-variant-numeric: tabular-nums; }
  td.amount { font-weight: 600; }

  /* Totals */
  .totals-section { display: flex; justify-content: flex-end; margin-top: 0; }
  .totals-table { width: 260px; }
  .totals-table tr td { padding: 5px 12px; font-size: 10.5px; }
  .totals-table tr td:last-child { text-align: right; font-variant-numeric: tabular-nums; }
  .totals-table .subtotal td { color: #555; }
  .totals-table .vat-row td { color: #555; }
  .totals-table .total-row { border-top: 2px solid #1a1a1a; }
  .totals-table .total-row td { font-size: 13px; font-weight: 800; color: #1a1a1a; padding-top: 8px; }

  /* Payment */
  .payment-section { margin-top: 28px; padding: 16px; background: #f0f9f4; border-radius: 8px; border: 1px solid #bee3cc; }
  .payment-title { font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.07em; color: #1a7a4a; margin-bottom: 8px; }
  .payment-link-label { font-size: 9.5px; color: #444; margin-bottom: 4px; }
  .payment-link { font-size: 10px; font-weight: 600; color: #1a7a4a; word-break: break-all; }
  .mpesa-note { margin-top: 6px; font-size: 9px; color: #666; }

  /* Notes */
  .notes-section { margin-top: 20px; padding: 12px 16px; background: #fafafa; border-radius: 6px; border-left: 3px solid #1a7a4a; }
  .notes-label { font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.07em; color: #888; margin-bottom: 4px; }
  .notes-text { font-size: 10px; color: #444; line-height: 1.6; }

  /* Footer */
  .footer { margin-top: 28px; padding-top: 12px; border-top: 1px solid #e5e5e5; display: flex; justify-content: space-between; align-items: center; }
  .footer-brand { font-size: 9px; color: #aaa; }
  .footer-brand strong { color: #666; }
  .footer-powered { font-size: 8.5px; color: #bbb; }

  /* Badges */
  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; }
  .badge-gray { background: #eee; color: #666; }
  .badge-blue { background: #dbeafe; color: #1e40af; }
  .badge-green { background: #dcfce7; color: #166534; }
  .badge-red { background: #fee2e2; color: #991b1b; }
</style>
</head>
<body>
<div class="page">

  <div class="header">
    <div class="brand">
      ${logoHTML}
      <div>
        <div class="biz-name">${escapeHtml(business.name)}</div>
        <div class="biz-meta">
          ${business.address ? escapeHtml(business.address) + '<br>' : ''}
          ${business.phone ? 'Simu: ' + escapeHtml(business.phone) + '<br>' : ''}
          ${business.email ? escapeHtml(business.email) + '<br>' : ''}
          ${business.tin ? 'TIN: ' + escapeHtml(business.tin) : ''}
          ${business.vrn ? ' | VRN: ' + escapeHtml(business.vrn) : ''}
        </div>
      </div>
    </div>
    <div class="invoice-meta">
      <div class="invoice-title">Invoice</div>
      <div class="invoice-number"># ${escapeHtml(invoice.number)}</div>
      <div style="margin-top:8px">${statusBadge}</div>
    </div>
  </div>

  <div class="parties">
    <div>
      <div class="party-label">Kutoka</div>
      <div class="party-name">${escapeHtml(business.name)}</div>
      <div class="party-detail">
        ${escapeHtml(business.address || '')}<br>
        ${business.tin ? 'TIN: ' + escapeHtml(business.tin) : ''}
      </div>
    </div>
    <div>
      <div class="party-label">Kwenda (Bill To)</div>
      <div class="party-name">${escapeHtml(invoice.client_name)}</div>
      <div class="party-detail">
        ${invoice.client_phone ? 'Simu: ' + escapeHtml(invoice.client_phone) + '<br>' : ''}
        ${invoice.client_email ? escapeHtml(invoice.client_email) + '<br>' : ''}
        ${invoice.client_address ? escapeHtml(invoice.client_address) + '<br>' : ''}
        ${invoice.client_tin ? 'TIN: ' + escapeHtml(invoice.client_tin) : ''}
      </div>
    </div>
  </div>

  <div class="dates-row">
    <div class="date-item">
      <div class="date-label">Tarehe ya Invoice</div>
      <div class="date-value">${formatDate(invoice.created_at)}</div>
    </div>
    <div class="date-item">
      <div class="date-label">Tarehe ya Mwisho</div>
      <div class="date-value">${invoice.due_date ? formatDate(invoice.due_date) : 'Haraka iwezekanavyo'}</div>
    </div>
    <div class="date-item">
      <div class="date-label">Sarafu</div>
      <div class="date-value">TZS (Shilingi ya Tanzania)</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th style="width:45%">Maelezo</th>
        <th class="num" style="width:10%">Idadi</th>
        <th class="num" style="width:20%">Bei/Kipande</th>
        <th class="num" style="width:25%">Jumla</th>
      </tr>
    </thead>
    <tbody>
      ${itemsHTML}
    </tbody>
  </table>

  <div class="totals-section">
    <table class="totals-table">
      <tbody>
        <tr class="subtotal">
          <td>Jumla Ndogo</td>
          <td>${formatTZS(invoice.subtotal)}</td>
        </tr>
        <tr class="vat-row">
          <td>VAT (${invoice.vat_rate}%)</td>
          <td>${formatTZS(invoice.vat_amount)}</td>
        </tr>
        <tr class="total-row">
          <td>JUMLA KUU</td>
          <td>${formatTZS(invoice.total)}</td>
        </tr>
      </tbody>
    </table>
  </div>

  ${
    invoice.payment_link
      ? `<div class="payment-section">
    <div class="payment-title">Lipa Sasa — Pay Now</div>
    <div class="payment-link-label">Bonyeza au scan link hii kulipa:</div>
    <div class="payment-link">${escapeHtml(invoice.payment_link)}</div>
    <div class="mpesa-note">Tunakubali: M-Pesa, Airtel Money, Tigo Pesa, kadi ya benki</div>
  </div>`
      : ''
  }

  ${
    invoice.notes
      ? `<div class="notes-section">
    <div class="notes-label">Maelezo / Notes</div>
    <div class="notes-text">${escapeHtml(invoice.notes)}</div>
  </div>`
      : ''
  }

  <div class="footer">
    <div class="footer-brand">
      <strong>${escapeHtml(business.name)}</strong> — ${escapeHtml(business.phone || '')} — ${escapeHtml(business.email || '')}
    </div>
    <div class="footer-powered">
      Imezalishwa na Blackwhite · blackwhite.co.tz
    </div>
  </div>

</div>
</body>
</html>`
}

// ============================================================
// Payslip HTML Template
// ============================================================
export async function renderPayslipHTML(payslip: Payslip, business: Business): Promise<string> {
  const logoHTML = await renderLogoHTML(business, 'logo')

  const allowancesHTML = payslip.allowances
    .map(
      (a) =>
        `<tr><td class="label">${escapeHtml(a.name)}</td><td class="num">${formatTZS(a.amount)}</td></tr>`
    )
    .join('')

  const deductionsHTML = [
    { name: 'PAYE (Kodi ya Mapato)', amount: payslip.paye },
    { name: 'NSSF (Mfanyakazi)', amount: payslip.nssf_employee },
    ...payslip.other_deductions,
  ]
    .map(
      (d) =>
        `<tr><td class="label">${escapeHtml(d.name)}</td><td class="num deduct">(${formatTZS(d.amount)})</td></tr>`
    )
    .join('')

  return `<!DOCTYPE html>
<html lang="sw">
<head>
<meta charset="UTF-8">
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px; color: #1a1a1a; background: #fff; }

  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 24px; padding-bottom: 16px; border-bottom: 2px solid #1a1a1a; }
  .brand { display: flex; align-items: center; gap: 12px; }
  .logo { height: 48px; width: auto; object-fit: contain; }
  .logo-placeholder { width: 48px; height: 48px; background: #1a7a4a; border-radius: 8px; display: flex; align-items: center; justify-content: center; color: white; font-size: 22px; font-weight: 700; }
  .biz-name { font-size: 16px; font-weight: 700; }
  .biz-meta { font-size: 9px; color: #666; margin-top: 2px; line-height: 1.6; }
  .slip-title { text-align: right; }
  .slip-heading { font-size: 22px; font-weight: 800; text-transform: uppercase; letter-spacing: -0.5px; color: #1a7a4a; }
  .slip-period { font-size: 11px; font-weight: 600; color: #444; margin-top: 4px; }

  .employee-box { background: #f5f5f2; border-radius: 8px; padding: 14px 16px; margin-bottom: 24px; display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; }
  .emp-label { font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.07em; color: #888; margin-bottom: 4px; }
  .emp-value { font-size: 12px; font-weight: 600; color: #1a1a1a; }

  .earnings-deductions { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 0; }
  .section-title { font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #888; margin-bottom: 8px; padding-bottom: 5px; border-bottom: 1px solid #e5e5e5; }

  table { width: 100%; border-collapse: collapse; }
  td { padding: 6px 0; font-size: 10.5px; border-bottom: 1px solid #f0f0f0; }
  td.label { color: #444; }
  td.num { text-align: right; font-variant-numeric: tabular-nums; font-weight: 500; }
  td.deduct { color: #dc2626; }
  .subtotal-row td { font-weight: 700; font-size: 11px; border-top: 1px solid #ccc; border-bottom: none; padding-top: 8px; }

  .net-pay-box { margin-top: 20px; background: #1a7a4a; border-radius: 8px; padding: 16px 20px; display: flex; justify-content: space-between; align-items: center; }
  .net-label { font-size: 12px; font-weight: 700; color: rgba(255,255,255,0.85); text-transform: uppercase; letter-spacing: 0.05em; }
  .net-sublabel { font-size: 9px; color: rgba(255,255,255,0.6); margin-top: 2px; }
  .net-amount { font-size: 24px; font-weight: 800; color: #fff; letter-spacing: -0.5px; font-variant-numeric: tabular-nums; }

  .nssf-note { margin-top: 14px; background: #fffbeb; border: 1px solid #fde68a; border-radius: 6px; padding: 10px 14px; }
  .nssf-title { font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.07em; color: #92400e; margin-bottom: 4px; }
  .nssf-text { font-size: 9.5px; color: #78350f; line-height: 1.5; }

  .sig-section { margin-top: 28px; display: grid; grid-template-columns: 1fr 1fr; gap: 40px; }
  .sig-line { border-top: 1px solid #ccc; padding-top: 6px; }
  .sig-label { font-size: 9px; color: #888; }

  .footer { margin-top: 24px; padding-top: 10px; border-top: 1px solid #e5e5e5; font-size: 8.5px; color: #bbb; text-align: center; }
</style>
</head>
<body>

  <div class="header">
    <div class="brand">
      ${logoHTML}
      <div>
        <div class="biz-name">${escapeHtml(business.name)}</div>
        <div class="biz-meta">
          ${escapeHtml(business.address || '')}<br>
          ${business.tin ? 'TIN: ' + escapeHtml(business.tin) : ''}
        </div>
      </div>
    </div>
    <div class="slip-title">
      <div class="slip-heading">Payslip</div>
      <div class="slip-period">${monthLabel(payslip.month)}</div>
    </div>
  </div>

  <div class="employee-box">
    <div>
      <div class="emp-label">Jina la Mfanyakazi</div>
      <div class="emp-value">${escapeHtml(payslip.employee_name)}</div>
    </div>
    <div>
      <div class="emp-label">Namba ya Mfanyakazi</div>
      <div class="emp-value">${escapeHtml(payslip.employee_id || '—')}</div>
    </div>
    <div>
      <div class="emp-label">Cheo / Position</div>
      <div class="emp-value">${escapeHtml(payslip.position || '—')}</div>
    </div>
  </div>

  <div class="earnings-deductions">
    <div>
      <div class="section-title">Mapato (Earnings)</div>
      <table>
        <tbody>
          <tr>
            <td class="label">Mshahara wa Msingi</td>
            <td class="num">${formatTZS(payslip.basic_salary)}</td>
          </tr>
          ${allowancesHTML}
          <tr class="subtotal-row">
            <td>Jumla ya Mapato</td>
            <td class="num">${formatTZS(payslip.gross)}</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div>
      <div class="section-title">Makato (Deductions)</div>
      <table>
        <tbody>
          ${deductionsHTML}
          <tr class="subtotal-row">
            <td>Jumla ya Makato</td>
            <td class="num deduct">(${formatTZS(payslip.total_deductions)})</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="net-pay-box">
    <div>
      <div class="net-label">Mshahara wa Mkono</div>
      <div class="net-sublabel">Net Pay — ${monthLabel(payslip.month)}</div>
    </div>
    <div class="net-amount">${formatTZS(payslip.net_pay)}</div>
  </div>

  <div class="nssf-note">
    <div class="nssf-title">Kumbuka — NSSF</div>
    <div class="nssf-text">
      Mchango wa mwajiri (NSSF Employer): ${formatTZS(payslip.nssf_employer)} — haujakatwa kwenye mshahara wako.
      Jumla ya mchango NSSF: ${formatTZS(payslip.nssf_employee + payslip.nssf_employer)}.
    </div>
  </div>

  <div class="sig-section">
    <div>
      <div class="sig-line"></div>
      <div class="sig-label">Sahihi ya Mwajiri / Employer Signature</div>
    </div>
    <div>
      <div class="sig-line"></div>
      <div class="sig-label">Sahihi ya Mfanyakazi / Employee Signature</div>
    </div>
  </div>

  <div class="footer">
    Hati hii imezalishwa kiotomatiki na Blackwhite · blackwhite.co.tz · ${new Date().toLocaleDateString('sw-TZ')}
  </div>

</body>
</html>`
}
